[2019-10-20 13:59:44,173] - Alog.py [Line:99] - [ERROR]-[thread:4738651584]-[process:25561] - another value is 322
[2019-10-20 14:01:40,143] - Alog.py [Line:45] - [ERROR]-[thread:4564170176]-[process:25582] - value is 222
[2019-10-20 14:01:40,143] - Alog.py [Line:54] - [ERROR]-[thread:4564170176]-[process:25582] - another value is 322
